### ISSUE TITLE
manual annotation supports species without iaclass configured

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#248]
**Desired Behavior**
`src/main/webapp/encounters/manualAnnotation.jsp`
1. Navigate to encounter and click hamburger menu on gallery
2. Click add annotation
4. select viewpoint
5. **drodown for Species**, select species
6. dropdown for IAClass, displays all IAclasses configured for specified species. If none, displays "none configured"; select an IAclass (which includes none configured)
8. draw annotation
9. click Save

_testing notes_
- iaclass should be none_configured for those that have "none configured" selected
- always creates a new encounter UNLESS: species matches current encounter species AND annotation IAClass is a part AND annotation is only part associated with encounter.

**Current Behavior**
1. Navigate to encounter and click hamburger menu on gallery
2. Click Add annotation
4. select viewpoint
5. draw annotation
6. dropdown only provides IAclasses that have ml configured to work

**Comment by NNattoji** [comment]
Tested locally using images from the web. 

### With iaClass Configured

Displays configured iaClass in the dropdown.

![iaClass_configured](https://github.com/WildMeOrg/Wildbook/assets/20950872/0dd80afd-30e8-49ac-b46b-25a3c32bc773)

### With no iaClass Configured

Displays 'none confgured' option with 'none_configured' value. Attaches to the same encounter for the first annotation and clones a new encounter for the second annotation.

![first_annotation_no_config](https://github.com/WildMeOrg/Wildbook/assets/20950872/08f4aca9-c508-415a-be2f-a31414cb35da)

![second_annotation_no_config](https://github.com/WildMeOrg/Wildbook/assets/20950872/13ca47ae-932f-4eff-88ef-b1dcfb3cbbb0)
