### ISSUE TITLE
iaResults Individual list doubled #1 match

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#254]
**Expected Behavior**
`/src/main/webapp/iaResults.jsp`
The best match displays once.

**Current Behavior**
(WB-1920)  When looking at IA results organized by Individual, the top Individual is shown twice vs annotations from different encounters. 

Investigation notes: The SQL query for the matching set looks normal, so it's likely this issue in in the javascript to display the score. 

**Community Link**
https://community.wildme.org/t/whiskerbook-individual-score-match-list-contains-individual-twice/1316

**Comment by holmbergius** [comment]
This was previously fixed due to a significant number of changes and improvements in iaResults.jsp as well as backend improvement in match results listing to avoid duplication.
