### ISSUE TITLE
Duplicate individuals can be created when an encounter deleted from a project is assigned an already-existing individual name

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#257]
(WB-1893)  Not sure whether this is the entire problem that Maureen is reporting, but this represents at least one circumstance where duplicate individual creation is possible.

Likely related to confirming no match in projects. Wildbook suggests an ID for the individual that's already been assigned.

**Community Link**
https://community.wildme.org/t/2-identical-marked-individuals/641/5
https://community.wildme.org/t/missing-submitter-id-causing-duplicates-in-new-id-uploads/1091/4
https://community.wildme.org/t/confirm-no-match-assigning-incorrect-id-in-iot/2114
https://community.wildme.org/t/error-processing-both-sides/2142
https://community.wildme.org/t/project-id-prefix/2501

May be related to https://github.com/WildMeOrg/Wildbook/issues/285

**Comment by goddesswarship** [comment]
This may have been resolved by #285 as there haven't been any reported duplicates since that fix went out.

**Comment by goddesswarship** [comment]
Closing as no new reports have surfaced I last commented in May.
