### ISSUE TITLE
Keywords are not alphabetized

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#261]
**Expected Behavior**
Keywords on the image should appear in alphabetical order both in display and in the selection list

**Current Behavior**
(WB-1873)

**Comment by naknomum** [comment]
here is a screengrab from the "fullscreen" view of images, from the encounter page. first of just the keywords as displayed, and then when you hover for editing.
![image](https://github.com/WildMeOrg/Wildbook/assets/901250/3a02c919-aa5d-4415-a2a7-80bbcd86706b)
![image](https://github.com/WildMeOrg/Wildbook/assets/901250/85a888b4-102e-4d60-a917-ac63a17aeea2)

**Comment by naknomum** [comment]
it appears that the [pulldown menu is created here](https://github.com/WildMeOrg/Wildbook/issues/261#issuecomment-1901066898). likely the display of the keywords is also in this same file.

**Comment by NNattoji** [comment]
PR created https://github.com/WildMeOrg/Wildbook/pull/359

Tested on local.

![Screen Shot 2024-01-26 at 3 01 33 PM](https://github.com/WildMeOrg/Wildbook/assets/20950872/f784e5d8-5f8b-49b8-8395-db7f298abe1a)

Keywords appear in alphabetical order after applying sorting.
