### ISSUE TITLE
Can't add comments to individuals.jsp page

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#270]
**Expected Behavior**
1. Go to any individual page
2. scroll all the way down to **researcher comments** with text box beneath
3. enter text into text box
4. click **add comment**
5. user stays on this page; comment is added to "researcher comments" log with correct time/date/username (following format of the other researcher comments)

**Current Behavior**
1. Go to any individual page 
2. scroll all the way down to **researcher comments** with text box beneath
3. enter text into text box
4. click **add comment** (ln 2542 in `/src/main/webapp/individuals.jsp`)
5. new page opens with text: "Failure: I do not have enough information to add your comments"

_Investigation notes:_
 I saw this in the logs when I reproduced customer's issue:

`17-Jun-2021 15:25:47.364 INFO [http-nio-8080-exec-5] org.datanucleus.store.rdbms.request.FetchRequest.execute Object with id "CH00021" not found!` 

**Conclusion**: that it's using the CH00021 individual name for something it should be using UUID for instead? (`value="<%=sharky.getName()%>"`)

**Community Link**
https://community.wildme.org/t/error-message-on-adding-comments-to-marked-individual-page/878

**Comment by Veda-Gogineni** [comment]
I am interested  to work on this repository. Could you please assign this issue to me.
