### ISSUE TITLE
"Occuring with" columns don't populate on individuals.jsp page

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#271]
**Expected Behavior**
1. Navigate to individual page
2. scroll down to encounter table or to co-occurrence table (tab next to co-occurrence diagram)
3. See name of individual that are seen with the individual on the current page

**Current Behavior**
1. Navigate to individual page
2. scroll down to encounter table or to co-occurrence table (tab next to co-occurrence diagram)
3. "occurring with" columns are empty

_Technical investigation_
`/src/main/webapp/individuals.jsp`

There is a co-occurrence diagram that _does_ populate with the "occurring with" individuals.

[live platform link to individual page](https://africancarnivore.wildbook.org/individuals.jsp?id=f8038d85-50c9-4366-87ac-5bda06bc684d)

**Community Link**
https://community.wildme.org/t/occurring-with-column-on-encounter-list-on-marked-ind-page-not-populating/850

**Comment by TanyaStere42** [comment]
@NNattoji I think this ticket covers the issue you referenced on #365 ?

**Comment by NNattoji** [comment]
The issue I saw was brought up in the Community Link shared above though and looks like the 'Occuring With' column issue is not happening anymore, based on the last comment in the link.

Hence I can apply the fix for the link issue as part of this ticket.

**Comment by NNattoji** [comment]
The issue reported on this ticket does not appear to be happening anymore, it's not seen while testing locally. The issue with the co-occurrence table link has been fixed in #410.

**Comment by TanyaStere42** [comment]
closed with #410
