### ISSUE TITLE
Fix Picturebook image cutoff

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#273]
**Expected Behavior**
`src/main/webapp/pictureBook.jsp?[searchquery]`
* 3 Pictures are all fully visible and grouped under a given individual in printed document, matching what is displayed in UI (image below)
![image](https://github.com/WildMeOrg/Wildbook/assets/62726866/7c547f59-0cb8-4e22-9f4f-44641a29bc9f)

**Current Behavior**
Couple probably-CSS issues with picturebook formatting:
 * Second line of pictures for an Individual is cut at the bottom in printed document (image below)
![image](https://github.com/WildMeOrg/Wildbook/assets/62726866/4e22978b-40d2-4e75-a447-4222a57742b0)

**Reproduction steps**
1. Upload 3 images and assign to one individual
2. Navigate to Individual Search
3. Search for that individual
4. On search results page, click Export Tab
5. Click export link. Wait for page to generate
6. Follow instructions at top of pictureBook.jsp to generate printed picture book

**Community Link**
 https://community.wildme.org/t/missing-individuals-in-picture-book/804/11

**Comment by NNattoji** [comment]
Tested on local with some images from the web. Could replicate the issue on local by uploading 3 images, 2 of the pictures were not showing in full while printing. All pictures show in full now while printing, after applying the CSS fix.
![Screen Shot 2024-02-27 at 10 05 24 AM](https://github.com/WildMeOrg/Wildbook/assets/20950872/898ca20a-f189-4652-8b69-7c3fd45542b1)
