### ISSUE TITLE
Manual annotation for unmatchable annotation still allows "Start another match" option.

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#276]
**Expected Behavior**
`src/main/webapp/encounters/manualAnnotation.jsp`
only iaClasses that have been configured in ia.json and commonconfig.properties are treated as matchable

**Current Behavior**
(WB-1564)  When an unmatchable iaClass is manually annotated, it has matchAgainst=true set. It should not.

**Community Link**
https://community.wildme.org/t/matching-not-doing-anything/675

**Comment by NNattoji** [comment]
The fix has been tested locally, 'Start Match' / 'Start Another Match' does not show for manual annotation after the fix.
![Screen Shot 2024-04-16 at 2 01 43 PM](https://github.com/WildMeOrg/Wildbook/assets/20950872/0fcaf36f-9b26-4eb4-a78c-31b76bfcbddf)
