### ISSUE TITLE
all viewpoints available in manual annotation tool

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#282]
**Expected Behavior**
1. User is on an encounter looking at gallery
2.  User selects **Add annotation** from hamburger menu ( opens `src/main/webapp/encounters/manualAnnotation.jsp`)
3. In Viewpoint dropdown, all viewpoints from `src/main/webapp/encounters/Annotation.java` are available. Dropdown also includes a value of `-----` to support viewpoint-less algorithms

ex: If VALID_VIEWPOINTS lists the following:
```
    private static final String[][] VALID_VIEWPOINTS = new String[][] {
        {"up",        "up",            "up",        "up",            "up",       "up",           "up",        "up",          },
        {"upfront",   "upfrontright",  "upright",   "upbackright",   "upback",   "upbackleft",   "upleft",    "upfrontleft"  },
        {"front",     "frontright",    "right",     "backright",     "back",     "backleft",     "left",      "frontleft"    },
        {"downfront", "downfrontright","downright", "downbackright", "downback", "downbackleft", "downleft",  "downfrontleft"},
        {"down",      "down",          "down",      "down",          "down",     "down",         "down",      "down"         }
};
```
Then the list should contain:
![Image](https://github.com/WildMeOrg/Wildbook/assets/62726866/be7e35e6-1e37-4dea-a56f-bd5db0806881)

Note that no duplicates are included

**Current Behavior**
1. User is on an encounter looking at gallery
2.  User selects **Add annotation** from hamburger menu ( opens `src/main/webapp/encounters/manualAnnotation.jsp`)
3. In Viewpoint dropdown, only the viewpoints that have been previously seen for a species are listed

**Community Link**
https://community.wildbook.org/t/missing-viewpoints-in-add-annotation-functionality/303/4

**Comment by NNattoji** [comment]
Feature tested locally using an image from the web. All viewpoints show up now after the feature implementation.

![Screen Shot 2024-04-30 at 11 14 50 AM](https://github.com/WildMeOrg/Wildbook/assets/20950872/a304fd1f-c4a5-4fc5-90c1-857b9c662390)
