### ISSUE TITLE
Adoptions still being solicited in Wildbooks

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#283]
**Open questions**
We need to preserve the adoption names that exist and credit those adopters, but remove the system charges. We should provide an alternative way for users to provide donations. One-time email alert is a good idea.

**Context**
Adoptions as they stand are not stable and have a negative impact on Wild Me image with citizen scientists in particular.

- Wildbook sends confirmation emails that prompt users to adopt their identified animal. However, adoptions are supposed to be disabled due to some payment processing issues.

<img src="https://github.com/WildMeOrg/Wildbook/assets/103530016/7bd757f3-5c18-48ab-b506-6effea52d747" width="500"/>

- Sharkbook prompts users on the individual page to nickname their shark, which opens an adoption payment page (https://community.wildme.org/t/unable-to-name-individuals/1858). 
- MantaMatcher user attempts to name manta and gets access denied error when they're prompted for adoption (https://community.wildme.org/t/access-denied-when-submitting-adoption/1955)
- Multiple users have stated they paid for an adoption but do not receive a) payment confirmation or b) acknowledgment in Wildbook that they are the adopter of the desired individual. (https://community.wildme.org/t/not-able-to-adoption-a-specific-individual/1781) 
(email from Carol at SAS-USA to Tanya and Anastasia Jan 30, 2021)
- When you submit an encounter to [Spot-a-Shark USA](https://ncaquariums.wildbook.org/submit.jsp), the footer of the confirmation page says "You can adopt a sand tiger shark and give it a nickname. To search for adoptable sharks and select one or more sharks to adopt, click the button below."

![Image](https://github.com/WildMeOrg/Wildbook/assets/103530016/d9ba55e3-6a33-4319-b23f-3bab6739d1c2)

**Comment by TanyaStere42** [comment]
Requires leadership intervention for payment processing so we can shut this down. Then plan is to remove all existing adoption functions and reimplement later as focused design effort

**Comment by goddesswarship** [comment]
I'm proactively removing the adoption role from current users, but we should also delete the role in Wildbooks where it's present.

**Comment by TanyaStere42** [comment]
Need to address `commonConfiguration.properties`
* `allowAdoptions` should be removed
* `adoptionLocation` can be maintained for data reference, but preferred that the data is preserved under a hardcoded database reference and this property removed. If not removed, needs a comment referencing that this is deprecated functionality that is maintained to preserve data integrity
* `adoptionCampaignUrl` should be removed
