### ISSUE TITLE
Encounter.state is case sensitive

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#284]
**Expected Behavior**
When Encounter.state is set from a bulk import, we should do some preprocessing to lowercase the state

**Current Behavior**
(WB-633)  Encounter state is a string field and is treated as case sensitive in searches, and when set from import- which is the only other way to set a value besides from the defines CC.props list.

**Community Link**
ttps://community.wildme.org/t/bulk-upload-approved-state-not-pulled-through-in-records/155

**Comment by NNattoji** [comment]
Tested on local after applying the fix.

Encounter.state set to 'Approved' in Import Excel, as shown in the parsed import table screenshot. This gets preprocessed to  'approved' and the encounter shows up under Approved Encounters on the website.
![Parsed Excel](https://github.com/WildMeOrg/Wildbook/assets/20950872/3026c3ab-135a-42e4-ba11-e1607e2f86ec)
![Approved Encounter](https://github.com/WildMeOrg/Wildbook/assets/20950872/e72cd744-6788-4c62-9caf-df4df0e48997)
