### ISSUE TITLE
Multiple pages for the same individual in Flukebook and ACW

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#285]
**Expected Behavior**
Each individual has a single page, regardless of where the individual was created. Any matching to an individual adds to the existing individual page.

**Current Behavior**
"A user uploaded 2 bulk imports with some of the same individual IDs across both spreadsheets. Flukebook now shows multiple pages with the same individual ID instead of merging the new IDs. Issue occurred for user when using Windows 10 Enterprise (version 21H2) and Chrome version 109.0.5414.210: https://www.flukebook.org/individualSearchResults.jsp?username=Sheila.Thornton

**Investigation notes**
Occuring in ACW as well: https://community.wildme.org/t/bulk-import-with-ids-creates-multiple-individual-records-with-the-same-id/1936 (resolved)
https://community.wildme.org/t/data-integrity-issue-duplicate-ids/2078/7 

**Community Link**
https://community.wildme.org/t/questions-about-matching/1918/7 (resolved)
https://community.wildme.org/t/bulk-import-with-ids-creates-multiple-individual-records-with-the-same-id/1936 (resolved)
https://community.wildme.org/t/data-integrity-issue-duplicate-ids/2078/7 (resolved)
https://community.wildme.org/t/id-s-not-merged-upon-import/2488 (resolved)
https://community.wildme.org/t/whiskerbook-user-reports-duplicate-ids/2549 (resolved)

May be related to confirming no match in projects. Wildbook suggests a number for the individual that's already been assigned: https://github.com/WildMeOrg/Wildbook/issues/257

**Comment by goddesswarship** [comment]
Resolved in Flukebook per https://github.com/WildMeOrg/Wildbook/pull/337

**Comment by goddesswarship** [comment]
Final individual reconciliation in ACW complete.
