### ISSUE TITLE
Update email template to explain unmonitored notification-only emails

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#290]
**Expected Behavior**
Add copy "Do not reply to this email. For questions and comments, go to [community.wildme.org]." Community.wildme.org should open in a new tab.

**Current Behavior**
Our encounter notification emails ([auto@iot.wildbook.org](mailto:auto@iot.wildbook.org), [webmaster.mantamatcher@wildme.org](mailto:webmaster.mantamatcher@wildme.org), etc.) don't have a footer explaining that these are notification-only addresses that can't receive messages.

**Comment by NNattoji** [comment]
The 'Do not reply to this email' message, as per the expected behaviour, has been added to the bottom of the new encounter submission emails. The community.wildme.org opens on a new tab. This has been tested on local.

![Screen Shot 2024-02-21 at 9 45 55 AM](https://github.com/WildMeOrg/Wildbook/assets/20950872/66cbd65e-aba1-4d70-ae52-1fff2dfd2210)

**Comment by goddesswarship** [comment]
@NNattoji Good question! I only had new encounter submission emails in mind, but I think it will be good to include it in other encounter notification emails for consistency.

**Comment by NNattoji** [comment]
Okay, I'll include it in other encounter notification emails too and update the opened PR as soon as I find a way to test it on local.

**Comment by NNattoji** [comment]
The message has been included in encounter update emails and tested on local. Test screenshot attached below for an encounter update scenario.
![Screen Shot 2024-02-22 at 10 06 21 AM](https://github.com/WildMeOrg/Wildbook/assets/20950872/ba567802-a8c6-4746-8ae8-71b50fb719c2)

**Comment by NNattoji** [comment]
@TanyaStere42 @goddesswarship The PR has been updated.
