### ISSUE TITLE
bulk import log page has locked link interactions

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#292]
**Expected Behavior**
All links on `imports.jsp` open new tabs to `target=_self`, middle click to `target=_blank`, and right click opens the standard menu

**Current Behavior**
- Can't right-click or scroll wheel click to open links in a new tab from bulk import page (/imports.jsp) but you can ctrl+click or cmd+click

**Comment by NNattoji** [comment]
All the different scenarios have been handled and tested locally on Safari, Chrome and Firefox. 

- Click (Left-click) opens with `target=_self`
- Middle-click and cmd+click opens with `target=_blank`
- Right-click and ctrl-click opens the menu

The menu which opens on right-click or ctrl + click is a browser default, the menu does not contain 'Open link in new tab' option (browsers show this only for anchor 'a' elements with 'href' attribute). The links on the page are clickable table row 'tr' elements, not anchor 'a' elements. The cell contents of the table are within 'div' elements, these could be changed to 'a' elements with 'href' attribute, if users are to have the option of navigating to the link through the right-click or ctrl + click menu.
