### ISSUE TITLE
Can't add assign orgs in GiraffeSpotter and issues creating new users.

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#294]
**Expected Behavior**
Existing User
1. go to user management, select user
2. make changes to that user's organizations and click save
3. Confirmation message; user's profile shows organization assignment

New User
1. go to user management, select user
2. make changes to that user's organizations and click save
3. user is created with new organization assignment

**Current Behavior**
As an admin user, I'm not able to add org assignments. 
Existing User
1. go to user management, select user
2. make changes to that user's organizations and click save
4. it goes to this URL which only displays a blank page (https://giraffespotter.org/UserCreate?context=context0&isEdit=true)
5. navigate away from and back to user manager; the changes are not saved.

New User 
1. go to user management and create new user, including adding an organization
2. click save, it goes to this URL with a blank page (https://giraffespotter.org/UserCreate?context=context0).
4. Navigate away and back and the user is ultimately created, but there's no confirmation message.

This is verified across different organizations and admin accounts. Editing other things in the user profile doesn't cause the blank page.

**Technical Notes**
Theory is that the code isn't generating a new row to save org assignments. 

**Support Team Workaround**
 manually update user via UUID. Not feasible as long-term solution

**Comment by goddesswarship** [comment]
Fixed per @holmbergius. Verified in testing that org assignments save correctly and creating a new user displays a success message.
