### ISSUE TITLE
Encounter confirmation emails are the same for registered users and the public

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#295]
**Expected Behavior**
email template is updated to clarify that you needed to have an account to view the link
"To view this link, sign in to your Wildbook account"

**Current Behavior**
Citizen scientists receive a confirmation email with a link to the encounter they submitted. However, public encounters are only visible to logged-in users. Non-registered can view marked individual pages without logging in on some Wildbooks (such as IoT and Spot-a-Shark, but not Whiskerbook).

**Community links:**
https://community.wildme.org/t/submitters-can-not-see-their-encounters/2203
https://community.wildme.org/t/seeing-my-submission-without-having-an-account/2040
https://community.wildme.org/t/citizen-scientists-unable-to-view-encounter-submission-in-flukebook/2296

**Comment by goddesswarship** [comment]
Worked with @holmbergius to review all Wildbooks and correct the security issue that a) did not assign new encounters from the public under the "public" ID and b) prevented public users from viewing their submitted encounters. Updates made to Flukebook, IoT, Spot-a-Shark USA, and Sharkbook are now live.
