### ISSUE TITLE
Remove Country drop-down menu from report encounter page in Whiskerbook

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#297]
**Expected Behavior**
`src/main/webapp/submit.jsp`
Country option does not display

**Current Behavior**
Country menu is still visible in Whiskerbook even though it's deprecated in favor of Location ID menu. New users tend to ask us to add items to it.

**Comment by goddesswarship** [comment]
I think this one can be closed as it may be an outdated request. https://community.wildme.org/t/add-remove-locationids-and-countries/2233/4
