### ISSUE TITLE
IoT: Inconsistent results in quick search bar

### ISSUE THREAD

**Issue by goddesswarship** [WildMeOrg/Wildbook#306]
**Expected Behavior**
The quick search bar on the top of the website displays a list of matches when an individual's ID or nickname is entered

**Current Behavior**
The quick search bar doesn't show matches for an exact individual ID, but only intermittently. When results do display, they all show with the previous search name in the results.

1. Search for "usv0184" yields no results
![Image](https://user-images.githubusercontent.com/103530016/256341708-751f0694-be4d-41d6-9d0f-f7c71a91edc5.png)

2. Search for "usv" yields no results
![Image](https://user-images.githubusercontent.com/103530016/256340504-9d1547f6-3fa7-4753-9a48-555f1a5ee083.png)

3. Search for "tuako" shows turtle nicknamed Tuako
![Image](https://user-images.githubusercontent.com/103530016/256340694-e9b1b287-ce3e-468f-8601-cff7181efe66.png)

4. Now search "usv" again. There are match results, but they all have Tuako next to the ID
![Image](https://user-images.githubusercontent.com/103530016/256340894-9f77eb17-b4ed-4954-bb8e-4465455e4fa6.png)

5. Search for "platypus" shows turtle nicknamed Platypus
![Image](https://user-images.githubusercontent.com/103530016/256342307-6e85dcfd-3638-4fd7-9a12-6e4956868c33.png)

6. Search "usv" again and there are now match results with Platypus next to the ID
![Image](https://user-images.githubusercontent.com/103530016/256341281-273a69d9-a253-4d6d-b765-50b9c8e57b1f.png)

**Community Link**
N/A. Reported during support call with user

**QA Notes**
Tested in Brave, Chrome, and Firefox. Could not reproduce in other Wildbooks (Flukebook, ACW, or Seadragon).

**Comment by TanyaStere42** [comment]
The new header design #417 does not incorporate the quick search bar, so we're closing this ticket.
