### ISSUE TITLE
Update autoreply email for Sharkbook

### ISSUE THREAD

**Issue by goddesswarship** [WildMeOrg/Wildbook#324]
**Current text**
"We will use your information to assist a global community of researchers and citizen scientists working to better understand and protect the world's biggest fish."

**Proposed text**
We will use your information to assist a global community of researchers and citizen scientists working to better understand and protect the world's shark species.

**Community link**
https://community.wildme.org/t/correction-to-sighting-autoresponder-on-sharkbook/2374

**Comment by TanyaStere42** [comment]
Fixed with [commit 6c1c54e](https://github.com/WildMeOrg/Wildbook/commit/6c1c54ed50d0e0abb6de35965f3d4f6b38a13563)
