### ISSUE TITLE
Broken link to help docs on Encounter page

### ISSUE THREAD

**Issue by goddesswarship** [WildMeOrg/Wildbook#327]
**Expected behavior**
Clicking on "Learn more" link next to Encounter page heading opens [Wildbook Overview help doc](https://docs.wildme.org/product-docs/en/wildbook/introduction/).

**Current behavior**
Clicking on "Learn more" link next to Encounter page heading goes to a [404 page](https://www.wildme.org/wildbook/doku.php?id=manual%3A2.0.x%3A1_overview).

![Image](https://github.com/WildMeOrg/Wildbook/assets/103530016/2a2e58a7-3b65-4a20-9b0a-1c572cff0ddd)

**QA notes**
This broken link appears in all Wildbooks except ACW and Wild North.

**Community link**
Reported via email to @goddesswarship by new Sharkbook user

**Comment by NNattoji** [comment]
The issue has been resolved by updating the link in encounter properties for all languages, using the link provided under Expected Behaviour, and tested on the local machine.
