### ISSUE TITLE
Typo on ARW homepage

### ISSUE THREAD

**Issue by goddesswarship** [WildMeOrg/Wildbook#341]
The [Amphibian-Reptile Wildbook](https://amphibian-reptile.wildbook.org/) homepage has a typo where it says "Wildbookbook" instead of "Wildbook"

![Image](https://github.com/WildMeOrg/Wildbook/assets/103530016/d911aed4-81cd-4188-a2b0-8f8d950b0583)

**Comment by TanyaStere42** [comment]
fixed by #591
