### ISSUE TITLE
No timeout warning before Wildbook signs users out for inactivity

### ISSUE THREAD

**Issue by goddesswarship** [WildMeOrg/Wildbook#354]
Wildbooks signs users out after a period of inactivity, but does not warn users before doing so. As a result, users in the middle of uploading encounters find that they have been signed out and that their private encounter data has been submitted as a public user, accessible to all researchers.

**Community link**
https://community.wildme.org/t/add-a-timeout-pop-up/2412

**Comment by TanyaStere42** [comment]
fixed by #427
