### ISSUE TITLE
Match results links open inconsistently

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#366]
**Expected Behavior**
All links on the `/iaResults.jsp?taskId=[guid]` page open new tabs to `target=_self`, middle click to `target=_blank`, and right click opens the standard menu

**Current Behavior**
- When on the match results page, you can't right-click, scroll wheel click, ctrl+click, or cmd+click to view the encounter page of the match candidate in a new tab. It will only open in the same window as the match page.

**Comment by NNattoji** [comment]
The fix has been tested locally across browsers through the match results obtained through detection and identification after integration with WBIA QA environment. The clickable element shows standard link behaviour now.
