### ISSUE TITLE
Coordinates are not editable at the Sighting level

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#370]
**Expected behavior**
Sighting latitude and longitude coordinates should be editable. 

* `src/main/webapp/occurrence.jsp` make lat/long editable 
  * follow pattern of `groupBehavior`
  * image button to edit
  * open modal
  * modal should have two number inputs with labels Latitude and Longitude
  * Save button should update database and close modal
* save button action should involve new class "OccurrenceSetLatLong" or similar name
  * follow pattern of `src/main/java/org/ecocean/servlet/OccurrenceSetGroupBehavior.java`

**Current behavior**
There is a field for the location coordinates on the sighting page, but it can't be edited here. A user has to edit each individual Encounter to change the coordinates.

**Community link**
https://community.wildme.org/t/possibility-to-change-gps-coordinates-sighting/2773/3

**Comment by TanyaStere42** [comment]
I mean, yea, that would be great 👍 Go for it!

**Comment by NNattoji** [comment]
Bearing and distance too have been made editable.

![Screen Shot 2024-04-29 at 4 28 36 PM](https://github.com/WildMeOrg/Wildbook/assets/20950872/31421e91-e6c1-401f-8e48-e68a622cde82)

Users have to provide latitude and longitude when making edits, while bearing and distance have been made optional.
