### ISSUE TITLE
Candidate images display wrong viewpoint for spot maps

### ISSUE THREAD

**Issue by goddesswarship** [WildMeOrg/Wildbook#395]
**Expected behavior**
Users see match results that correspond with their shark's viewpoint (lefts matched to lefts, rights matched to rights).

**Current behavior**
Users see match results for a different viewpoint than their source image. I verified that the source and candidate viewpoints were all labeled correctly: 
- https://www.sharkbook.ai/encounters/scanEndApplet.jsp?rightSide=false&taskID=scanL0e604d2c-1185-4908-9bf2-0b45c7072fec&writeThis=true&number=0e604d2c-1185-4908-9bf2-0b45c7072fec&viewresult=View
- https://www.sharkbook.ai/encounters/scanEndApplet.jsp?rightSide=false&taskID=scanLbe0dea0d-76c2-4c81-bb70-a1e02551cfbe&writeThis=true&number=be0dea0d-76c2-4c81-bb70-a1e02551cfbe&viewresult=View
- https://www.sharkbook.ai/encounters/scanEndApplet.jsp?rightSide=false&taskID=scanLffcc16a2-eeb4-473b-b996-d3d2809debd9&writeThis=true&number=ffcc16a2-eeb4-473b-b996-d3d2809debd9&viewresult=View

**Community link**
https://community.wildme.org/t/sharkbook-bug-comparing-left-flank-to-right-flanks/2706

**Comment by TanyaStere42** [comment]
verifying this isn't an issue on sea bass; once that is confirmed, this will just be addressed with release of the new ml update for sharks

**Comment by goddesswarship** [comment]
I spot-checked (heh) 10 different spot maps in Sea Bass and all candidate viewpoints matched the source image.

**Comment by JasonWildMe** [comment]
@TanyaStere42 Can this be closed?

**Comment by JasonWildMe** [comment]
No further work needed.
