### ISSUE TITLE
Individual id is not getting appended properly to the Co-occurrences table

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#410]
**Expected Behavior**
1. Navigate to Individual Page
2. Scroll to co-occurrence table
3. click on individual name
4. get navigated to the new individuals

**Current Behavior**
1. Navigate to Individual Page
2. Scroll to co-occurrence table
3. click on individual name
4. page does not open correctly

_Technical Investigation_
Another existing issue was seen, in the Co-occurrences table on Individuals page, while applying fix for this issue. Individual id is not getting appended properly to the Co-occurrences table links, hence clicking on the table rows does not navigate to proper URLs.

![Screen Shot 2024-03-14 at 6 14 48 PM](https://github.com/WildMeOrg/Wildbook/assets/20950872/378a6984-6523-4d18-bea4-1aef44a30f9e)

![Screen Shot 2024-03-14 at 6 14 55 PM](https://github.com/WildMeOrg/Wildbook/assets/20950872/0d4ac9b3-d615-4c21-9ab0-ea96d1ac0aa3)

This is happening because the individual display name is being used while forming the URL, the id (UUID) is to be used instead. If there is a ticket for this or if a ticket is created, I can create a PR with the fix.

_Originally posted by @NNattoji in _https://github.com/WildMeOrg/Wildbook/issues/365#issuecomment-1998727320_
_Additional context https://github.com/WildMeOrg/Wildbook/issues/271#issuecomment-2004531657_

**Comment by NNattoji** [comment]
This has been fixed and tested locally. The co-occurrence table link works fine now and navigates to the correct URL, while the value in the 'Occuring With' column shows the display name as before.
