### ISSUE TITLE
display media asset file name as uploaded

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#412]
Context
Wildbook currently does filename processing to remove characters from bulk import file names

To allow for easy reconciliation between files in system and external to the system, we need to display the filename as it was originally uploaded, regardless of what preprocessing we do. This means that the original filename should be stored as a string and used for display.
(update to `parameters` json for `MediaAsset`)

Current Behavior
file Caitlánn*Survey_10293.jpg displays as Caitl_nn_Survey_10293.jpg

Expected Behavior
file Caitlánn*Survey_10293.jpg displays as Caitlánn*Survey_10293.jpg

_Technical Notes_
Design/architecture patterns should be the same between #372 and this ticket

Acceptance Criteria
Display is updated on the following pages to show the original file name:
- `/src/main/webapp/obrowse.jsp` (parameters display)
- `/src/main/webapp/iaResults.jsp` (display on both target and query)
- `/src/main/webapp/encounters/encounterMediaGallery.jsp` (encounter, gallery, click image for overlay)
- `/src/main/webapp/encounters/encounter.jsp` (adding image to encounter)
- `/src/main/webapp/encounters/thumbnailSearchResults.jsp` (individual, view all images, click image for overlay)
- `/src/main/webapp/import/reviewDirectory.jsp` (list shows preprocessing)
- `/src/main/java/org/ecocean/servlet/importer/StandardImport.java` (displays in verification table)
- `/src/main/java/org/ecocean/servlet/export/EncounterSearchExportMetadataExcel.java` (encounter standard export)

Community link
https://community.wildme.org/t/underscores-dashes-no-longer-displaying-or-exporting-correctly/2721

**Comment by naknomum** [comment]
for the single submit/form flavor, likely place to fix: `makeMediaAssetsFromJavaFileItemObject()`

**Comment by Paul-Kalil** [comment]
Hi Tanya, any sense of when 10.2.0 milestone will be set?  I have a number of large users holding off on Catalog bulk uploads until this is fixed.  I just need some help managing expectations.  Thanks. Paul

**Comment by TanyaStere42** [comment]
10.2.0: Must include our first unit test and then we'll turn on codecov
