### ISSUE TITLE
Public Encounter data is too restricted

### ISSUE THREAD

**Issue by goddesswarship** [WildMeOrg/Wildbook#416]
**Expected behavior**
When viewing an encounter submitted by username "public" (`/encounters/encounter.jsp`), the following metadata is visible to any viewer, even when not signed in:
- Location description
- Location ID
- Encounter date
- Latitude/Longitude
- Photographer
- Submitter

**Current behavior**
Some metadata became more restricted after a security update. When viewing an encounter submitted by username "public" (`/encounters/encounter.jsp`), the following metadata is only visible to users who are signed into Wildbook. This can discourage citizen scientists from staying engaged if they can't see certain encounter details of public submissions.

**Context**
@goddesswarship discussed this with @holmbergius and determined that security updates made to Wildbooks in Feb 2024 introduced a bug that made public Encounter data more restricted. This is especially a blocker for Wildbooks with a large citizen scientist focus as these submitters are emailed when an individual they've encountered is seen again. Now they can't follow the link in their email to view the new public encounter details like they could before because it's blocked by Silo security.

**Community link**
https://community.wildme.org/t/privacy-settings-changed/2778

**Comment by Veda-Gogineni** [comment]
I have few doubt:
1. Can we give access for "Public" user to edit the metadata? 
2. Do I need to show GPS data for Public user?

**Comment by TanyaStere42** [comment]
Public users should only _see_ the specific data we listed. They cannot edit the data at all.

GPS data should be restricted to signed-in users
