### ISSUE TITLE
Wildbook Login Success page references different Wildbook in role assignments

### ISSUE THREAD

**Issue by goddesswarship** [WildMeOrg/Wildbook#423]
**Expected behavior**
In Wildbook's Login Success page (`/LoginUser`) and Create/Edit User confirmation pages (`/UserCreate`) it displays only the user's assigned roles with no additional context.

list from below would read (no context, no punctuation):
- admin
- researcher
- rest
- machinelearning
- orgAdmin

**Current behavior**
Whiskerbook, Deerspotter, and Sharkbook's Login Success page (`/LoginUser`) and Create/Edit User confirmation pages (`/UserCreate`) displays the Wildbook name (often the incorrect Wildbook name) next to the roles to provide context. 

<img src="https://github.com/WildMeOrg/Wildbook/assets/103530016/3d429334-19a3-4ba2-90a1-9d8e45fd800c" width="500">

**Technical notes**
`src/main/java/org/ecocean/servlet/UserCreate.java` addedRoles > remove context so list just displays `roles[i]` to just display the roles assigned
ex: `Flukebook.org:admin` becomes `admin` in the list

**Community link**
https://community.wildme.org/t/referencing-wrong-wildbook-on-login-page/2878

**Comment by NNattoji** [comment]
Tested locally after applying the fix, roles show without context now on Login Success page (/LoginUser) and Create/Edit User confirmation pages (/UserCreate).

![Screen Shot 2024-05-01 at 10 17 09 AM](https://github.com/WildMeOrg/Wildbook/assets/20950872/dbccb6df-e257-4e0d-95a8-62027e122c0a)

![Screen Shot 2024-05-01 at 10 19 28 AM](https://github.com/WildMeOrg/Wildbook/assets/20950872/1874d2f8-eaf3-41ac-bb6c-700198e33748)
