### ISSUE TITLE
responsive design issues in sign in page

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#502]
**Current Behavior**
1. Go to sign-in page
2. Adjust screen width to be narrow
3. See clipping across the components
![image](https://github.com/user-attachments/assets/ccf97f0c-356b-401a-88c7-cf452e7865cd)

**Expected Behavior**
1. Go to sign-in page
2. Adjust screen height to be narrow
3. interaction fields/buttons are above background, if any overlap occurs OR scrollbar instead of clipping

**Comment by MukarramHaq** [comment]
Hello, I would like to work on this issue.

**Comment by TanyaStere42** [comment]
Hi @MukarramHaq ! We'd be happy to have you work on this. I'm in the process of updating our build instructions to address the addition of react. If you want to join the discord for information on that, we can probably get you going on this no-problem
