### ISSUE TITLE
Base class

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#509]
## Feature description and context
To simplify the integration of OpenSearch, we want to eliminate the potential for a great deal of redundant code functions and references across our "main" classes. To do this, we'll start by taking functionality that is common across classes and creating a base class which these will inherit from.

## Feature sign-off requirements
- Encounter.java, Occurrence.java, and MarkedIndividual.java behavior, methods, etc. unchanged.
- "fundamental" methods on above work from base class - probably abstracts that rely on above classes to return values -- including but not limited to:
  - `getId()` (String)
  - `getVersion()` (long) - each class above might have slightly different value this will be computed from, for example `modified` property (a date/time) on Encounter
- Comment all methods that should get replaced with this base class with `## DEPRECATED #509 - Base class`

## Architectural Design Notes
- will not change underlying column names in DB (for id)

**Comment by NNattoji** [comment]
The base class has been created.
