### ISSUE TITLE
password visibility toggle

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#516]
## Feature description and context
When signing in, a user may be unsure in what they entered when typing their password. Making a toggle button to display/mask the entered password will make this process easier (and is something of an industry standard)

## Feature sign-off requirements
- leverage material icons
- eye: password text is visible
- eye closed/slashed out: password text is masked
- either way, submission validation process works

**Comment by PAVANA809** [comment]
Generated PR #746
