### ISSUE TITLE
Missing space between # and "Annotations" in login landing page (React)

### ISSUE THREAD

**Issue by holmbergius** [WildMeOrg/Wildbook#521]
**Expected Behavior**

- Space between the # and the word "Annotations" is missing

**Current Behavior**
See below.

**Testing Notes**

- Test 1 annotations and multiple annotations

![image](https://github.com/WildMeOrg/Wildbook/assets/154927/f0edde2a-d5bd-493d-b2c3-a53f78609721)

**Comment by TanyaStere42** [comment]
note on image example: we are not implementing (s) on plural objects

**Comment by naknomum** [comment]
> note on image example: we are not implementing (s) on plural objects

just curious if this is because we want to save this for later when we address i18n as a whole? (that is: using `react-intl` to _properly_ handle the pluralization of _Annotation_.)

**Comment by TanyaStere42** [comment]
> > note on image example: we are not implementing (s) on plural objects
> 
> just curious if this is because we want to save this for later when we address i18n as a whole? (that is: using `react-intl` to _properly_ handle the pluralization of _Annotation_.)

mainly it's because we do not do this practice consistently and I'm making the style decision that, at this point, if it's generally a plural, we're gonna treat it as a plural and not worry about the case where it's singular. We can worry about that case later.
