### ISSUE TITLE
metrics update for public vs non-researcher vs researcher

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#532]
## Feature description and context
Improvement of metrics for narrative storytelling support. we want to be able to track citizen scientist contributions vs researcher contributions

## Feature sign-off requirements
Query:
- number of public encounters: encounters submitted by `submitterID == "public"`
- number of encounters submitted by citizen scientist: encounters submitted by accounts that do not have a role
- number of encounters submitted by researcher: encounters submitted by accounts that have researcher, orgadmin, or admin roles

**Comment by holmbergius** [comment]
@TanyaStere42 Are these encounter counts or user counts? I think "Contribution" is confusing me.

**Comment by TanyaStere42** [comment]
Encounter count
