### ISSUE TITLE
Landing Page Button Not Populated Correctly with Username Until After Long Data Load

### ISSUE THREAD

**Issue by holmbergius** [WildMeOrg/Wildbook#545]
**Expected Behavior**
Right arrow always works on page and leads to an Encounter Search populated with my data.

![image](https://github.com/WildMeOrg/Wildbook/assets/154927/bd7da1e7-db41-464b-b97b-41ddddb86f53)

**Current Behavior**
The right arrow on the landing page can have a bad URL (?username=undefined) before an API call populates it correctly and therefore lead to an unpopulated Encounter Search result (appears to user as missing data) while it is doing a large data load on the Landing Page. For users with very small datasets, that component loads fast, and they might not get the bad link. But for people with a large data load, it may be many seconds before the correct API call populates the link. Anyone who just wants to move on with the button without waiting for the component to load will experience this.

**Testing Notes**
Test for users with large datasets.

**Comment by erinz2020** [comment]
actually after merging in PR538 this right arrow button will be replaced with a spinner when data is loading, 
but it's possible to keep this right arrow button(together with spinner) and use another /user api to get username, instead of the current api(/home) which takes time to load

**Comment by holmbergius** [comment]
Replacing it with the spinner works. Thank you! Users have the menu at the top to also get to Encounter Search, so this button isn't a blocker IMHO.

**Comment by erinz2020** [comment]
pr#538 fixes this bug
