### ISSUE TITLE
change success confirmation to alert instead of different page on individual comment add

### ISSUE THREAD

**Issue by goddesswarship** [WildMeOrg/Wildbook#576]
**Current behavior**
When adding comments to a Marked Individual page (`/individuals.jsp`), the user is taken to a new page with only a success message that they have to click their browser's back button to exit. 

![Image](https://github.com/WildMeOrg/Wildbook/assets/103530016/3429cb36-c84f-4a6a-9b6f-f0a5133b183d)

Adding a comment should keep user on the same page and show the new comment in the Research Comments log.

**Steps to reproduce**
1. Scroll down to Research Comments section of Marked Individual page
2. Add comments
3. Click Add Comments button
4. Get taken to new page that says "Success: I have successfully added your comments."

Related to https://github.com/WildMeOrg/Wildbook/issues/270

**Comment by sloviclana** [comment]
Hi, I am interested in working on this issue. Could you assign it to me please?

**Comment by TanyaStere42** [comment]
If you have any questions, feel free to ask questions here or join the Wild Me discord :)

**Comment by maisie-fisher** [comment]
Hi! I would like to work on this ticket - could you assign it to me?

**Comment by TanyaStere42** [comment]
Hey @maisie-fisher ! Hope things are going well. Need any support on this?

**Comment by maisie-fisher** [comment]
Hi! @TanyaStere42 I have everything set up and been working on it but ran into some issues - hoping to come to the Wednesday support session!

**Comment by TanyaStere42** [comment]
Gotcha, look forward to chatting there 😁
