### ISSUE TITLE
update all references from login.jsp to Login.jsx

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#592]
## Feature description and context
With the new react login page, we need to make sure that we are updating throughout the platform to get rid of any outdated references to the jsp page so we can eventually remove the jsp

## Feature sign-off requirements
- LoginUser.java: comments and string url
- DELETE: LoginUserSocial: comments, string url, geturl requests, redirects
- DELETE: SocialConnect.java: comments, geturl requests, redirects
- DELETE: SocialGrabFiles.java: comments, redirects, geturl requests
- DELETE: UserCreateSocial.java: comments, redirects
- UserResetPassword.java: geturl requests
- index.jsp: comment
- web.xml: comments, login url

## Technical notes
If any additional references to login.jsp are found, feel free to update those as well. call them out in the PR

**Comment by erinz2020** [comment]
notes to future me:
also fix the logout.jsp issue

**Comment by erinz2020** [comment]
add the "redirect user after login" feature, need Jon's help
