### ISSUE TITLE
Admin logs page - react update

### ISSUE THREAD

**Issue by pratisthabuddhacharya** [WildMeOrg/Wildbook#607]
## Feature description and context
We need to redesign the logs page ([url]/appadmin/logs.jsp) to align with the new Wild Me theme.

## Feature sign-off requirements
**Non-functional-requirements**
- should match the design and be responsive
- should use wildbook's components, text and color styles
- text is internationalized
- unit test that links work

**Functional requirements**
- page can be found at new url: `[url]/react/admin/logs`
- header navigation reference is updated to point at the new page across all headers
   - `frontend/src/constants/navMenu.js`
   - `src/main/webapp/header.jsp`
   - `src/main/resources/servletResponseTemplate.htm`
- clicking the cards should take you to correct pages
   - User Access Logs `[wildbook-url]/wildbook_data_dir/logs/user-access.htm`
   - Encounter Submission Logs `[wildbook-url]/wildbook_data_dir/logs/encounter-submission.htm`
   - Deleted Encounter Logs `[wildbook-url]/wildbook_data_dir/logs/encounter-delete.htm`
   - Email Logs `[wildbook-url]/wildbook_data_dir/logs/email.htm`

## Design
- [Figma Link](https://www.figma.com/design/C333OScEwSKMDW5NFXrp5s/List-of-Logs?node-id=3-3)

- Component list/reference
   - Header - Signed In
   - Footer
   - Cards (#789 )

- images needed
   - [listoflogs.zip](https://github.com/user-attachments/files/15832152/listoflogs.zip)

- Screenshots
    
![Image](https://github.com/WildMeOrg/Wildbook/assets/101117101/645336bc-7b92-4f3e-9702-69af8ebabef3)

**Comment by PAVANA809** [comment]
@TanyaStere42 i will work on this
