### ISSUE TITLE
React Component: Cards

### ISSUE THREAD

**Issue by pratisthabuddhacharya** [WildMeOrg/Wildbook#608]
## Feature description and context
We need card components for the List of Logs Page {https://[wildbook-url]/appadmin/logs.jsp} These cards will be used in different situations, so we need to create flexible components.

## Feature sign-off requirements
 - [ ] should match the design and be responsive 
 - [ ] should have 4 different instance
   - Instance 01: Icon, Title
   -  Instance 02: Icon, Title, Content, CTA
   -  Instance 03:  Title, Content, CTA
   -  Instance 04: Icon, Title, Content
 - [ ] is available with other react components

## Design
- [Figma link](https://www.figma.com/design/Wy0ZS11i2LsZI5rYWkd7iO/Wildbook---Style-%26-Components?node-id=710-10417&t=oH3VMq7aTB3ZAtDg-11)
- [How to use?](https://www.figma.com/design/Wy0ZS11i2LsZI5rYWkd7iO/Wildbook---Style-%26-Components?node-id=710-19800&t=oH3VMq7aTB3ZAtDg-11)
- [Example use case](https://www.figma.com/design/C333OScEwSKMDW5NFXrp5s/List-of-Logs?node-id=3-3)

> ![Image](https://github.com/WildMeOrg/Wildbook/assets/101117101/42c33883-f3b0-4fb1-98dc-4f292591338a)

**Comment by Avinashshiyani** [comment]
I can help you with that

**Comment by TanyaStere42** [comment]
@Avinashshiyani That would be great! I can assign this to you

**Comment by TanyaStere42** [comment]
Hey @Avinashshiyani , how are things going? Need any support on this?

**Comment by TanyaStere42** [comment]
Reassigning due to lack of response
