### ISSUE TITLE
Repository description link is outdated

### ISSUE THREAD

**Issue by ZumZoom** [WildMeOrg/Wildbook#609]
The link in the About section of the repository is outdated.

https://www.wildme.org/codex-and-wildbook.html

It leads to a deleted webpage.

**Comment by TanyaStere42** [comment]
@erinz2020 I can't find link in the code anymore; I think this was resolved with the header updates (#578). What do you think?

**Comment by erinz2020** [comment]
> @erinz2020 I can't find link in the code anymore; I think this was resolved with the header updates (#578). What do you think?

@TanyaStere42 it might have been replaced by the new header, I need to confirm.
may I know where you saw the link on the page? @ZumZoom

**Comment by ZumZoom** [comment]
It is in the about section of the repo:

<img width="1624" alt="Screenshot 2024-06-26 at 10 17 26" src="https://github.com/WildMeOrg/Wildbook/assets/735355/31f4c0e2-db64-4593-9c59-1adae6dde9e8">

**Comment by TanyaStere42** [comment]
Oh! thanks for catching that. It's been updated!
