### ISSUE TITLE
Remove Youtube Intelligent Agent

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#622]
**Open Questions**
What to do with the generated location IDs per platform

**Context**
youtube IA was a valuable tool in assessing how to do web scraping for citizen scientist entries, but there are concerns with the implementation that have led to the need to pull the feature from the platform.

**Comment by naknomum** [comment]
paying particular attention to disabling **stanford-parser** as much as possible.

**Comment by TanyaStere42** [comment]
closed by #706 . Not sure why it didn't link automatically?
