### ISSUE TITLE
encounter.state SiteSettings API addition

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#627]
## Feature description and context
In support of the React front end, we need APIs for all valid value lists. `encounter.state` is one of them!
Note: related to #626, but not dependent.

## Feature sign-off requirements
- GET the encounter state via the SiteSettings API, which can have one of the following values:
  - `unapproved` (default)
  - `approved`
  - `unidentifiable`

## Technical Notes
- functionality shall be extended in the existing `api/SiteSettings.java` servlet, using the api key `encounterStates`
- use a hard-coded array of strings for the values (defined as a class variable). however please put a note in a comment above it that historically this list was generated via CommonConfiguration using `List<String> states = CommonConfiguration.getIndexedPropertyValues("encounterState",context)`
- see `sex` being set via `VALUES_SEX = { "unknown", "male", "female" }` as an example.

**Comment by PAVANA809** [comment]
Generated pull request
https://github.com/WildMeOrg/Wildbook/pull/747
