### ISSUE TITLE
update in-product references to point to new search page

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#648]
## Feature description and context
Final piece to encounter search update: update all links that go to encounter search

## Feature sign-off requirements

1. Header (update across all header styles):
  - Search > Encounter (current: `/encounters/encounterSearch.jsp`)
  to `/react/encounter-search` no filters
  - My Data > My encounters (current: `/encounters/searchResults.jsp?username=[USERNAME]`)
  to `react/encounter-search` filter assignedUsername = current user
  - My Data > My encounters > My approved animals (current: `https://seal-wildbook.wildme.dev/encounters/searchResults.jsp?username=tomcat&state=approved`)
  to `react/encounter-search` filter assignedUsername=[CURRENTUSER] AND state=approved
  - My Data > My encounters > My unapproved animals (current: `https://seal-wildbook.wildme.dev/encounters/searchResults.jsp?username=tomcat&state=unapproved`)
  to `react/encounter-search` filter assignedUsername=[CURRENTUSER] AND state=unapproved
  - My Data > My encounters > My unidentifiable animals (current: `https://seal-wildbook.wildme.dev/encounters/searchResults.jsp?username=tomcat&state=unidentifiable`)
  to `react/encounter-search` filter assignedUsername=[CURRENTUSER] AND state=unidentifiable
2. My Account page (`/myAccount.jsp`):
  - Learn more about the encounters assigned to your account (current: `/encounters/searchResults.jsp?username=[USERNAME]`)
  to `react/encounter-search` filter assignedUsername=[CURRENTUSER]
3. landing page (`/react/`):
  - Latest data -> (current: `/encounters/searchResults.jsp?username=[USERNAME]`)
  to `react/encounter-search` filter assignedUsername = current user
4. project page `projects/project.jsp?id=xxx`
  - Encounter search page (current: `/encounters/encounterSearch.jsp`)
  to `/react/encounter-search` no filters

**Comment by erinz2020** [comment]
and also the project page: projects/project.jsp?id=xxx   Encounters can be added to this project from the[ Encounter search page](http://frontend.scribble.com/react/encounter-search), where they can be added by clicking on

**Comment by TanyaStere42** [comment]
good catch! requirements updated

**Comment by TanyaStere42** [comment]
all verified on QA. approved once out of draft
