### ISSUE TITLE
sign in banner

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#744]
## Feature description and context
If a user is not signed in during submission, they should be reminded with a banner at the top of the screen

## Feature sign-off requirements
**Non-Functional requirements**
- PR needs to branch off of feature branch: `submission_page`

**Functional requirements**
- Banner displays when signed in
- Banner does not display when signed in
- When "sign in" link is clicked, user is navigated to `react/signin`; after signed in, they are returned to the submission page

## Design
![Image](https://github.com/user-attachments/assets/0f1d484f-c670-4fda-ab49-958355311044)
[Full prototype design](https://www.figma.com/design/Iu28ZpOjgVIiRNaYlqSacY/Submit%3A-Location-ID?node-id=4459-40902&node-type=section&t=s14j4ZYxNL7ytHaM-0)

**Comment by PAVANA809** [comment]
@TanyaStere42 I will work on this
