### ISSUE TITLE
image upload component

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#750]
## Context
We need photo upload across different pages. Might as well make it a component 😃 

## Sign off requirements
**Non-functional requirements**
- PR must go to feature branch `submission_page`

**Functional requirements**
- supports jpg, jpeg, png, and bmp
- drop folders/image or click to browse
- displays thumbnail of file uploaded
- x to remove uploaded file
- button to "add more files" if any files have already been uploaded
- fail state "failed to upload images"

## Designs
[Link to Prototype](https://www.figma.com/proto/Iu28ZpOjgVIiRNaYlqSacY/Submit%3A-Location-ID?node-id=4411-77534&starting-point-node-id=4411%3A77534)

Initial state: no images uploaded
![Image](https://github.com/user-attachments/assets/00412867-45af-45b2-9080-6e0743515f48)
State in-use: images uploaded
![Image](https://github.com/user-attachments/assets/ec11e9b3-2895-45f9-bc12-8ebb8a57bd09)

**Comment by naknomum** [comment]
investigate existing mechanism for _adding images to encounters_ to see what might be reusable. very likely some backend code can be recycled. maybe also frontend.

**Comment by erinz2020** [comment]
Maximum uploadable media size: maxMediaSize from commonConfiguration.properties
fail state "The file is too large. Please upload a file smaller than [maxSize] MB."?
may need to show in photo upload requirement copy
