### ISSUE TITLE
followup information frame

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#795]
## Context
The new submit page is intended to lead users through the submission process in a more procedural way; final step is to provide any information for people who were associated with getting the encounter data or those who want to be informed of changes to the encounter such as matches made

## Signoff
**Non-Functional Requirement**
- PR needs to branch off of feature branch: `submission_page`

**Functional Requirement**
- followup information frame description, headers, and field labels (#738 )
- submitter fields include:
   - name (text field)
   - email (text field)
      - email format validation: check for `@` and check for `.` in order
      - if fails validation, do not send to BE during submission
- photographer fields include:
   - name (text field)
   - email (text field)
      - email format validation: check for `@` and check for `.` in order
      - if fails validation, do not send to BE during submission
- others to inform field
   - email (text field, supports comma separated list)
      - email format validation: check for `@` and check for `.` in order
      - if fails validation, do not send to BE during submission
- anchor and scroll still functional (#749 )

## Design
[static files](https://www.figma.com/design/Iu28ZpOjgVIiRNaYlqSacY/Submit%3A-Location-ID?node-id=4459-23131&node-type=frame&t=s14j4ZYxNL7ytHaM-0)
[prototype](https://www.figma.com/proto/Iu28ZpOjgVIiRNaYlqSacY/Submit%3A-Location-ID?page-id=3%3A3&node-id=4411-77534&node-type=section&viewport=568%2C443%2C0.06&t=7myMJfMJzVdYfru6-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=4411%3A77534&show-proto-sidebar=1)

![Image](https://github.com/user-attachments/assets/5ee946ea-d540-4533-b9c6-6278e55fbc85)

**Comment by PAVANA809** [comment]
@TanyaStere42 I can work on this after implementation of mobx
