### ISSUE TITLE
additional comments frame

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#796]
## Context
The new submit page is intended to lead users through the submission process in a more procedural way; next-to-last step is to allow users to enter freeform comments that could be useful for research

## Signoff
**Non-Functional Requirement**
- PR needs to branch off of feature branch: `submission_page`

**Functional Requirement**
- additional comments frame description (#738 )
- additional comment field
   - long text (no more than 5000 characters)
- anchor and scroll still functional (#749 )

## Design
[static file](https://www.figma.com/design/Iu28ZpOjgVIiRNaYlqSacY/Submit%3A-Location-ID?node-id=4459-23131&node-type=frame&t=s14j4ZYxNL7ytHaM-0)
[prototype](https://www.figma.com/proto/Iu28ZpOjgVIiRNaYlqSacY/Submit%3A-Location-ID?page-id=3%3A3&node-id=4411-77534&node-type=section&viewport=568%2C443%2C0.06&t=7myMJfMJzVdYfru6-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=4411%3A77534&show-proto-sidebar=1)

![Image](https://github.com/user-attachments/assets/d80f5882-12a7-43a0-984f-120d6d7bacef)

**Comment by PAVANA809** [comment]
@TanyaStere42 I will work on this after implementation of mobx
