### ISSUE TITLE
species frame

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#797]
## Context
The new submit page is intended to lead users through the submission process in a more procedural way; one step is to require users to select species for matching purposes

## Signoff
**Non-functional Requirement**
- PR needs to branch off of feature branch: `submission_page`

**Functional Requirement**
- species frame description (#738 )
- species field
   - species is shown to be required, displaying the asterisk (*)
   - throws the error message "This field cannot be empty" if the user tries to submit without select a species
   - dropdown list populated by configured species (see `/frontend/src/components/filterFields/ObservationAttributeFilter.jsx` for usage)
   - also includes "unknown" as option
- anchor and scroll still functional (#749 )

## Design
[Static figma](https://www.figma.com/design/Iu28ZpOjgVIiRNaYlqSacY/Submit%3A-Location-ID?node-id=4459-32252&node-type=frame&t=eVADCq9WBfhTDuEo-0)
[Protoype - Report Encounter Forest](https://www.figma.com/proto/Iu28ZpOjgVIiRNaYlqSacY/Submit%3A-Location-ID?page-id=3%3A3&node-id=4411-77534&node-type=section&viewport=568%2C443%2C0.06&t=7myMJfMJzVdYfru6-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=4411%3A77534&show-proto-sidebar=1)

Initial state
![Image](https://github.com/user-attachments/assets/8bbb353f-81b4-4e92-adc2-6da01e3eb407)
Error message state: submitted empty
![Image](https://github.com/user-attachments/assets/466e966a-3002-49e1-b70b-8fa17cfc96ec)

**Comment by PAVANA809** [comment]
@TanyaStere42 I will work on this
