### ISSUE TITLE
update encounter search page scroll behavior

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#809]
## Context
The usability of the current encounter search page gets a little weird with double scrolling. By applying the improved design from the submission page, we can improve the user experience and nail down a consistent pattern in the UI

The page structure is created in #749 

## Feature sign-off requirements
- [x] Page categories are static
- [x] Page anchors link off the category navigation
- [x] Right panel is scrollable

## Design
- [Figma link](https://www.figma.com/proto/Iu28ZpOjgVIiRNaYlqSacY/Submit%3A-Location-ID?page-id=3%3A3&node-id=4411-77534&node-type=section&viewport=568%2C443%2C0.06&t=7myMJfMJzVdYfru6-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=4411%3A77534) is to the submission prototype, which leverages same page structure

**Comment by goddesswarship** [comment]
Looks good!
