### ISSUE TITLE
Special characters in email address prevent password reset from saving

### ISSUE THREAD

**Issue by goddesswarship** [WildMeOrg/Wildbook#814]
**Expected Behavior**
Requesting a password reset allows a user to set and save a new password.

**Current Behavior**
If an email address is used as a username and it contains a `+` in the email address (like handle+test@website.org) entering a new password from the password reset page (`/UserResetPassword`) fails with this error message:

`Failure: Password was NOT successfully reset. I could not find the specified user.`

**Testing Notes**
Once I logged back into my admin account and gave my test account a username without special characters, it accepted the password reset attempt.

**Comment by Rodhlann** [comment]
Assign to me please!

**Comment by goddesswarship** [comment]
Per feedback from @Rodhlann this may have been resolved as part of a previous update as we're no longer able to replicate this in dev or prod. Marking as closed.
