### ISSUE TITLE
Encounter Submission Confirmation Page

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#827]
## Context
With the creation of the Submission page, we need to create a new confirmation page

## Sign-off Requirements
**Non-functional requirements**
- PR must come from the branch `submission_page`
- localization is done for all 5 supported languages

**Functional requirements**
- has standard react header and footer in place
- url is `react/reportConfirm/`
- copy ([encounter_submission_copy.txt](https://github.com/user-attachments/files/17300237/encounter_submission_copy.txt)) is correct for title, header, summary information, contact directive, banner content, and button labels
- View Encounter button navigates to encounter page for newly created encounter
- Submit Next Encounter navigates to `submit/report/`
- contact directive link navigates to community.wildme.org
- Summary information displays:
   - Encounter guid
   - LocationID
   - Submission Date
   - Image thumbnails and filename
- Banner displays if images were not able to be uploaded
   - Banner lists which files did not upload by filename
   - Banner photo requirements link navigates to wildbook.docs.wildme.org/data/photography-guidelines.html

## API Technical notes
- The submission creation API will return a JSON body response upon success (a `200` return code and `success: true` in the JSON)
- The results will contain key/values for the newly created Encounter guid (key `id`) as well as `locationID` and `submissionDate` values for display
- It will also contain an array `assets` (when applicable) which will contain JSON objects for each image added, with values for `filename` and `thumbnailUrl` in each item.
- An array `invalidFiles` will be present if there were images that were not valid
- Any other return codes (`40x`, `500`, etc) should be treated as an error. In most error cases, the JSON body should contain an array called `errors` which will include JSON objects representing problems, using localized codes for each error type, such as `REQUIRED` or `INVALID` along with the fieldname which failed. (However, some 500 errors will not return valid JSON, so the error code alone should trigger a generic error message in this case.)

## Design
[figma static design](https://www.figma.com/design/qXnOHpFmO7nFwT0IBkhKxl/Encounter-Submission---Success%2FError?node-id=3-3&node-type=canvas&t=TBBLOPy60fI9WJ2w-0)

All images uploaded successfully
![Image](https://github.com/user-attachments/assets/21cc965d-6d5a-4059-9e23-b17377c26208)

Some images failed to upload
![Image](https://github.com/user-attachments/assets/1b76b557-9a1d-46f5-badc-2e1f8f99f824)

**Comment by PAVANA809** [comment]
@TanyaStere42 I will work on this
