### ISSUE TITLE
Can't assign orgs in Seal Wildbook

### ISSUE THREAD

**Issue by goddesswarship** [WildMeOrg/Wildbook#841]
Related to #294 

**Expected Behavior**
1. go to user management, select user
2. make changes to that user's organizations and click save
3. Confirmation message; user's profile shows organization assignment

**Current Behavior**
1. go to user management, select user
2. make changes to that user's organizations and click save
3. blank page loads
4. navigate away from and back to user manager; the changes are not saved.

**Testing Notes**
Reference Notion doc on adding new orgs and assigning users via URL: https://www.notion.so/Add-new-org-caba025a27314127b58d5fa24c01a577

@TanyaStere42 verified that managing org assignments in QA user management works as intended. 

@naknomum Deleting org names has to happen at the database level (I don't have instructions for how to do that). Feel free to delete and clean up the current orgs so I can eventually add a simplified org name.

**Comment by goddesswarship** [comment]
Ticket info based on testing and discussion in dev office hours 10/22/24

**Comment by goddesswarship** [comment]
@naknomum We think this is the commit from #294 that fixed the org issue: https://github.com/WildMeOrg/Wildbook/commit/0cd7134f30e3238a8aa9c111036da19c700156c1

There doesn't appear to be an associated PR.

**Comment by TanyaStere42** [comment]
closed with patch treatment to branch
