### ISSUE TITLE
IA error when special character is present in "id" of locationID.json

### ISSUE THREAD

**Issue by goddesswarship** [WildMeOrg/Wildbook#844]
**Expected behavior**
When selecting a location ID, matches appear based on the chosen location ID.

**Current behavior**
When location IDs with special characters are selected, (such as O'ahu), matching does not complete and returns an IA error message.

**Investigation notes**
Relevant section in locationID.json:

`{ "name":"O'ahu", "id":"O'ahu", "locationID":[] },`

**Community link**
https://community.wildme.org/t/match-results-error-in-iot/3441

**Comment by goddesswarship** [comment]
Wrote up ticket based on discussion with @holmbergius in Slack.

**Comment by goddesswarship** [comment]
locationID.json updated and backed up to Github (https://github.com/WildMeOrg/Wildbook/commit/317fe764deddb94261fff917a99ed23ee160b6e1). May also need to be updated in the database per @holmbergius. Waiting for test match to complete to verify.

**Comment by goddesswarship** [comment]
Makes sense. The code was a hot mess! I did my best with code cleanup and updated associated encounters. Database changes in progress.

**Comment by TanyaStere42** [comment]
yea, not surprising at all :sweat: I think this should be manual database changes and then just standard monitoring of entered location IDs (until we get away from config eventually), no new dev

**Comment by goddesswarship** [comment]
Testing is showing match results loading now. Closing.
