### ISSUE TITLE
linter to take into account node.js

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#867]
## Feature description and context
We're using node.js but our linter does not recognize it, requiring manual adjustments to avoid errors being thrown. We want to adjust configuration so node.js is recognized and processing is handled automatically.

## Feature sign-off requirements
- node.js: true for eslinter
- removal of all inline comments that were used for manual adjustments
   - this line used before process.env   `// eslint-disable-next-line no-undef`
   - this line at the top of files `/* eslint-disable no-undef */`
- resolve any undefined references that were missed through manual adjustments

**Comment by Rodhlann** [comment]
@TanyaStere42 I can look in to this one, assign to me, please!
