### ISSUE TITLE
Alphabetize viewpoints in manual annotation workflow

### ISSUE THREAD

**Issue by goddesswarship** [WildMeOrg/Wildbook#870]
**Expected behavior**
Viewpoints are displayed alphabetically in the manual annotation workflow (/encounters/manualAnnotation.jsp)

**Current behavior**
Viewpoints are not displayed alphabetically

<img src="https://github.com/user-attachments/assets/f68d3c8e-1ebe-473d-ae2a-5dc73ad198df" width="300">

**Community link**
https://community.wildme.org/t/viewpoint-alphabetical-order/4388

**Comment by Nomop** [comment]
Hi @TanyaStere42  ! Can i work on this issue although I am new . Can you assign it to me?

**Comment by TanyaStere42** [comment]
Absolutely! 😁

**Comment by Nomop** [comment]
I have made the changes, how can I merge them to master

**Comment by goddesswarship** [comment]
@Nomop You won't be able to merge until your PR has been reviewed by one of us. I'll add reviewers to your PR.
